export const GET_CHAT_PENDING = "GET_CHAT_PENDING";
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAIL = "GET_CHAT_FAIL";

export const NEW_CHAT_PENDING = "NEW_CHAT_PENDING";
export const NEW_CHAT_SUCCESS = "NEW_CHAT_SUCCESS";
export const NEW_CHAT_FAIL = "NEW_CHAT_FAIL";
