export const GET_CHAT_PENDING = "GET_CHAT_PENDING";
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAIL = "GET_CHAT_FAIL";

export const NEW_CHAT_PENDING = "NEW_CHAT_PENDING";
export const NEW_CHAT_SUCCESS = "NEW_CHAT_SUCCESS";
export const NEW_CHAT_FAIL = "NEW_CHAT_FAIL";

export const GET_MESSAGE_PENDING = "GET_MESSAGE_PENDING";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MESSAGE_FAIL = "GET_MESSAGE_FAIL";

export const NEW_MESSAGE_PENDING = "NEW_MESSAGE_PENDING";
export const NEW_MESSAGE_SUCCESS = "NEW_MESSAGE_SUCCESS";
export const NEW_MESSAGE_FAIL = "NEW_MESSAGE_FAIL";
